name: Test 🧪
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    paths:
      - 'lib/src/**'
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.js'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x', '24.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - name: Run Unit Tests
        run: npm run test:cov
      - name: Upload Test Coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}